yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutMePage.as_view(), name='me'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/<int:post_id>/', views.post_detail, name='post_detail'),
    path('<username>/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('<username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'
handler500 = 'posts.views.server_error'

urlpatterns = [
    path('staff/admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %} 
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% include 'includes/nav.html' %}
  </div>
</nav>   

yatube/templates/includes/nav.html
{% with request.resolver_match.view_name as view_name %}
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"> 
      <a class="nav-link {% if view_name  == 'about:me' %}active{% endif %}" 
        href="{% url 'about:me' %}">
        Об авторе
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
        href="{% url 'about:tech' %}">
        Технологии
      </a>
    </li>
    {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link " 
          href="{% url 'posts:post_create' %}">
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
          href="{% url 'users:password_change' %}">
          Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">
          Выйти
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'posts:profile' %}active{% endif %}" 
          href="{% url 'posts:profile' user.username %}">
          Пользователь: {{ user.username }}.
        </a>
      </li>
    {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">
          Регистрация
        </a>
      </li>
    {% endif %}
  </ul>
{% endwith %} 