yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutMePage.as_view(), name='me'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/<int:post_id>/', views.post_detail, name='post_detail'),
    path('<username>/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('<username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'
handler500 = 'posts.views.server_error'

urlpatterns = [
    path('staff/admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/posts/models.py
import textwrap

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Название группы'
    )
    slug = models.SlugField('Адрес', unique=True, help_text='Адрес группы')
    description = models.TextField('Описание', help_text='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


    def __str__(self):
        return str(self.title)


class Post(models.Model):
    text = models.TextField('Текст', help_text='Текст поста')
    pub_date = models.DateTimeField(
        'Дата пуликации',
        auto_now_add=True,
        help_text='Дата публикации поста'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Связанная группа'
    )
    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку',
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


    def __str__(self):
        fullname = self.author.get_full_name()
        slug = self.author.username
        res = f'Автор: {fullname} ({slug})\n'
        res += f'Группа: {self.group}\n'
        res += f'Дата публикации: {self.pub_date.date()}\n'
        shorten_text = textwrap.shorten(
            text=self.text,
            width=20,
            placeholder='...'
        )
        res += f'Текст: {shorten_text}'
        return res


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        related_name='comments',
        help_text='Комментируемый пост',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments',
        help_text='Автор комментария'
    )
    text = models.TextField('Текст', help_text='Текст комментария')
    created = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True,
        help_text='Дата добавления комментария',
        db_index=True
    )

    class Meta():
        ordering = ('created', )
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


    def __str__(self):
        fullname = self.author.get_full_name()
        slug = self.author.username
        res = f'Автор: {fullname} ({slug})\n'
        res += f'Текст: {self.text}\n'
        res += self.created.strftime('%b %d, %Y, %H:%M')
        return res


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower',
        help_text='Подписчик автора'
    )
    following = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following',
        help_text='Автор'
    )

    class Meta():
        ordering = ('following', )
        verbose_name = 'Подписческа'
        verbose_name_plural = 'Подписчески'
        unique_together = ('user', 'following',)

    def __str__(self):
        return (f'Подписка {self.user.get_full_name()} '
                f'({self.user.username}) на {self.following.get_full_name()} '
                f'({self.following.username})')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from yatube.settings import ELEMENTS_PER_PAGE

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post

User = get_user_model()


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('group').all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'group': group,
        'page': page
    }
    return render(request, template, context)


def profile(request, username):
    user = request.user
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = False
    try:
        Follow.objects.get(user=user, author=author)
    except ObjectDoesNotExist:
        pass
    except MultipleObjectsReturned:
        following = True
    else:
        following = True
    finally:
        context = {
            'author': author,
            'page': page,
            'following': following
        }
        return render(request, template, context)


def post_detail(request, username, post_id):
    template = 'posts/post_detail.html'
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, pk=post_id)
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            Comment.objects.create(
                post=post,
                text=form.cleaned_data['text'],
                author=request.user,
            )
    form = CommentForm()
    context = {
        'author': author,
        'post': post,
        'form': form
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            Post.objects.create(
                text=form.cleaned_data['text'],
                author=request.user,
                group=form.cleaned_data['group'],
                image=form.cleaned_data['image']
            )
            return redirect('posts:index')
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, pk=post_id)
    if request.user != author:
        return redirect('posts:post_detail', author.username, post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if request.POST and form.is_valid():
        form.save()
        return redirect('posts:post_detail', author.username, post_id)
    return render(request, 'posts/create_post.html',
                  {'is_edit': True, 'form': form, 'post': post})


@login_required
def add_comment(request, username, post_id):
    template = 'posts/comment.html'
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(author.posts, pk=post_id)
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            Comment.objects.create(
                post=post,
                text=form.cleaned_data['text'],
                author=request.user,
            )
        return redirect('posts:post_detail', author.username, post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def follow_index(request):
    user = request.user
    authors = []
    for follow in Follow.objects.filter(user=user):
        authors.append(follow.author)
    posts = Post.objects.filter(author__in=authors)
    paginator = Paginator(posts, ELEMENTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/follow.html', {'page': page})


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        if not Follow.objects.filter(user=user, author=author).exists():
            Follow.objects.create(
                user=user,
                author=author
            )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:follow_index')


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)

yatube/templates/posts/comment.html
{% extends 'base.html' %}
{% block title %}
    Добавить комментарий
{% endblock %}
{% block content %}
  {% include 'posts/includes/comments.html' %}
{% endblock %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load custom_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
              {% endif %}
              <div class="card-body">        
                <form 
                  method="post"
                  enctype="multipart/form-data"
                  {% if is_edit %}
                  action="{% url 'posts:post_edit' user post.id %}"
                  {% else %}
                  action="{% url 'posts:post_create' %}" 
                  {% endif %}>
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row" aria-required={{ field.field.required }}>
                    <label
                      for="{{ field.id_for_label }}"
                      class="col-md-4 col-form-label text-md-right">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required">*</span>
                      {% endif %}
                    </label>
                    <div class="col-md-6">
                      {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                   </div>
                  </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content %}
  {% include 'posts/includes/menu.html' with follow=True %}
  <div class="container py-5">
    <h1>Избранные авторы</h1>
    {% for post in page %}
      {% include 'posts/includes/post_item.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }} | Yatube
{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <h1>{{ group }}</h1> 
    <p> 
      {{ group.description }} 
    </p> 
    {% for post in page %} 
      {% include 'posts/includes/post_item.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  <title>Страница группы {{ group.title }}</title>
{% endblock %}
{% block content %} 
  <div class="container"> 
    <h1>{{ group }}</h1> 
    <p> 
      {{ group.description }} 
    </p> 
    {% for post in posts %} 
      <article> 
        <ul> 
          <li> 
            Автор: {{ post.author.get_full_name }} 
          </li> 
          <li> 
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li> 
        </ul> 
        <p>{{ post.text }}</p> 
      </article> 
      <hr>
    {% endfor %}  
  </div> 
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  <title>Последние обновления на сайте</title>
{% endblock %}
{% block content %}
  <div class="container">
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if post.group != Null %}
        {% if post.group != '' %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы {{ post.group.title }}</a>
        {% endif %}
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}
  Пост {{ post.text|maketitle }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: 
            <a href="{% url 'posts:group' post.group.slug %}">
              {{ post.group.title }}
            </a>
          </li>
        {% endif %}
              
        <li class="list-group-item">
          {% include 'posts/includes/author_card.html'%}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% include 'posts/includes/post_item.html'%}
      {% if user == author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' author.username post.pk %}">
        редактировать запись
      </a>
      {% endif %}
      {% include 'posts/includes/comments.html' %}
    </article>
  </div> 
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Все посты пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <li class="list-group-item">
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button">
        Подписаться
      </a>
    {% endif %}
  </li>
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>   
      {% for post in page %}
        {% include 'posts/includes/post_item.html' %}
      {% if post.group != Null %}
        {% if post.group != '' %}
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы {{ post.group.title }}</a>
        {% endif %}
      {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}