yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutMePage.as_view(), name='me'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        views.LoginView.as_view(
            template_name='users/login.html',
            redirect_field_name='posts:profile'
        ),
        name='login'
    ),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'
handler500 = 'posts.views.server_error'

urlpatterns = [
    path('staff/admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Вы вышли из системы</div>
        <div class="card-body">
          <p> Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}

{% block content %}
  {% load custom_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              Имя пользователя и пароль не совпадают. Введите правильные данные.
            </div>
          {% endif %}

          {% if next %}
            <div class="alert alert-info" role="alert">
              Вы обратились к странице, доступ к которой возможен
              только для залогиненных пользователей.<br>
              Пожалуйста, авторизуйтесь.
            </div>
          {% else %}
            <div class="alert alert-info" role="alert">
              Пожалуйста, авторизуйтесь.
            </div>
          {% endif %}

          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="form-group row">
              <label
                for="{{ form.username.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Имя пользователя
              </label>
              <div class="col-md-6">
                {{ form.username }}
              </div>
            </div>

            <div class="form-group row">
              <label
                for="{{ form.password.id_for_label }}"
                class="col-md-4 col-form-label text-md-right">
                Пароль
              </label>
              <div class="col-md-6">
                {{ form.password }}
              </div>
            </div>

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
  {% load custom_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  <span class="required">*</span>
                </label>
                <div class="col-md-6">
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля выполнен{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Сброс пароля выполнен</div>
        <div class="card-body">
          <p>Пароль изменён, всё получилось.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}

{% block content %}
  {% load custom_filters %}
  {% if validlink %}

    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">

            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ field.label }}: {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
            {% endif %}

            <form method="post">
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  <span class="required">*</span>
                </label>
                <div class="col-md-6">
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
              {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>

  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Ссылка на восстановление пароля отправлена{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ссылка на восстановление пароля отправлена</div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  {% load custom_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты,
          под которым вы регистрировались
        </div>
        <div class="card-body">

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  <span class="required">*</span>
                </label>
                <div class="col-md-6">
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {% load custom_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}